routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'TopicsController@index')->name('top');
Route::resource('topics', 'TopicsController', ['only' => ['create', 'store', 'show', 'edit', 'update', 'destroy']]);
Route::resource('comments', 'CommentsController', ['only' => ['store', 'edit', 'update', 'destroy']]);

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'user_name',
        'message',
    ];

    public function topic()
    {
        return $this->belongsTo('App\Topic');
    }
}

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $fillable = [
        'user_name',
        'title',
    ];

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Topic;

class CommentsController extends Controller
{
    /*
     * 登録処理
     */
    public function store(Request $request)
    {
        $params = $request->validate([
            'topic_id' => 'required|exists:topics,id',
            'user_name' => 'max:32',
            'message' => 'required|max:2048',
        ]);

        $topic = Topic::findOrFail($params['topic_id']);
        $topic->comments()->create($params);

        return redirect()->route('topics.show', ['topic' => $topic]);
    }

    /*
     * 編集画面
     */
    public function edit($comment_id)
    {
        $comment = Comment::findOrFail($comment_id);

        $topic = Topic::findOrFail($comment->topic_id);

        return view('comments.edit', [
            'comment' => $comment,
            'topic' => $topic,
        ]);
    }

    /*
     * 更新処理
     */
    public function update($comment_id, Request $request)
    {
        $params = $request->validate([
            'user_name' => 'max:32',
            'message' => 'required|max:2048',
        ]);

        $comment = Comment::findOrFail($comment_id);
        $comment->fill($params)->save();

        $topic = Topic::findOrFail($comment->topic_id);

        return redirect()->route('topics.show', ['topic' => $topic]);
    }

    /*
     * 削除処理
     */
    public function destroy($comment_id)
    {
        $comment = Comment::findOrFail($comment_id);
        $topic = Topic::findOrFail($comment->topic_id);

        DB::transaction(function () use ($comment) {
            // TODO: フラグ管理したいかも
            $comment->delete();
        });

        return redirect()->route('topics.show', ['topic' => $topic]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TopicsController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Topic;

class TopicsController extends Controller
{
    /*
     * スレッド一覧
     */
    public function index()
    {
        $topics = Topic::with(['comments'])->orderBy('created_at', 'desc')->paginate(10)->onEachSide(1);
        return view('topics.index', ['topics' => $topics]);
    }

    /*
     * 編集ページ
     */
    public function create()
    {
        return view('topics.create');
    }

    /*
     * 登録
     */
    public function store(Request $request)
    {
        $params = $request->validate([
            'user_name' => 'max:32',
            'title' => 'required|max:64',
        ]);

        Topic::create($params);

        return redirect()->route('top');
    }

    /*
     * 詳細表示
     */
    public function show($topic_id)
    {
        $topic = Topic::findOrFail($topic_id);
        $comments = $topic->comments()->paginate(25);

        return view('topics.show', ['topic' => $topic, 'comments' => $comments]);
    }

    /*
     * 編集画面
     */
    public function edit($topic_id)
    {
        $topic = Topic::findOrFail($topic_id);

        return view('topics.edit', [
            'topic' => $topic,
        ]);
    }

    /*
     * 更新処理
     */
    public function update($topic_id, Request $request)
    {
        $params = $request->validate([
            'user_name' => 'max:32',
            'title' => 'required|max:64',
        ]);

        $topic = Topic::findOrFail($topic_id);
        $topic->fill($params)->save();

        return redirect()->route('topics.show', ['topic' => $topic]);
    }

    /*
     * 削除処理
     */
    public function destroy($topic_id)
    {
        $topic = Topic::findOrFail($topic_id);

        DB::transaction(function () use ($topic) {
            // TODO: スレッドは削除ではなくフラグ管理したいかも
            $topic->comments()->delete();
            $topic->delete();
        });

        return redirect()->route('top');
    }
}

resources/views/comments/edit.blade.php
@extends('layout')

@section('content')

    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                コメントの編集
            </p>
        </header>

        <div class="card-content">
            <div class="content">

                <form method="POST" action="{{ route('comments.update', ['comment' => $comment]) }}">

                    @csrf
                    @method('PUT')

                    <div class="field">
                        <label class="label" for="user_name">投稿者名</label>
                        <div class="control">
                            <input id="user_name" name="user_name"
                                   class="input {{ $errors->has('user_name') ? 'is-danger' : '' }}" type="text"
                                   placeholder="スレッド投稿者名。" value="{{ old('user_name') ?: $comment->user_name }}">
                        </div>

                        @if($errors->has('user_name'))
                            <p class="help is-danger">{{ $errors->first('user_name') }}</p>
                        @endif

                    </div>

                    <div class="field">
                        <label class="label" for="message">メッセージ</label>
                        <div class="control">
                                <textarea id="message" name="message"
                                          class="textarea {{ $errors->has('message') ? 'is-danger' : '' }}"
                                          placeholder="Textarea">{{ old('message') ?: $comment->message }}</textarea>
                        </div>

                        @if($errors->has('message'))
                            <p class="help is-danger">{{ $errors->first('message') }}</p>
                        @endif
                    </div>

                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-link" type="submit">編集する</button>
                        </div>
                        <div class="control">
                            <a class="button is-text" href="{{ route('topics.show', ['topic' => $topic]) }}">キャンセル</a>
                        </div>
                    </div>


                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BBS</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>

<header>
    <nav class="navbar is-light" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ url('') }}">シンプルな掲示板</a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{ url('') }}">スレッド一覧</a>
            </div>
        </div>
    </nav>
</header>


<section class="section">
    <div class="container">
        @yield('content')
    </div>
</section>

</body>
</html>

resources/views/topics/create.blade.php
@extends('layout')

@section('content')


    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                スレッドの新規作成
            </p>
        </header>
        <div class="card-content">
            <div class="content">

                <form method="POST" action="{{ route('topics.store') }}">

                    @csrf

                    <div class="field">
                        <label class="label" for="title">スレッド名</label>
                        <div class="control">
                            <input id="title" name="title" class="input {{ $errors->has('title') ? 'is-danger' : ''}}"
                                   type="text" placeholder="スレッド名をここにいれてください。" value="{{ old('title') }}">
                        </div>
                        @if($errors->has('title'))
                            <p class="help is-danger">{{ $errors->first('title') }}</p>
                        @endif
                    </div>

                    <div class="field">
                        <label class="label" id="user_name">投稿者名</label>
                        <div class="control">
                            <input id="user_name" name="user_name" class="input {{ $errors->has('user_name') ? 'is-danger' : '' }}" type="text" placeholder="スレッド投稿者名。"
                                   value="{{ old('user_name') }}">
                        </div>
                        @if($errors->has('user_name'))
                            <p class="help is-danger">{{ $errors->first('user_name') }}</p>
                        @endif
                    </div>

                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-link" type="submit">作成する</button>
                        </div>
                        <div class="control">
                            <a class="button is-text" href="{{ route('top')  }}">キャンセル</a>
                        </div>
                    </div>

                </form>


            </div>
        </div>
    </div>


@endsection

resources/views/topics/edit.blade.php
@extends('layout')

@section('content')

    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                スレッドの編集
            </p>
        </header>

        <div class="card-content">
            <div class="content">

                <form method="POST" action="{{ route('topics.update', ['topic' => $topic]) }}">
                    @csrf
                    @method('PUT')


                    <div class="field">
                        <label class="label" for="title">スレッド名</label>
                        <div class="control">
                            <input id="title" name="title" class="input {{ $errors->has('title') ? 'is-danger' : ''}}"
                                   type="text" placeholder="スレッド名をここにいれてください。"
                                   value="{{ old('title') ?: $topic->title }}">
                        </div>
                        @if($errors->has('title'))
                            <p class="help is-danger">{{ $errors->first('title') }}</p>
                        @endif
                    </div>

                    <div class="field">
                        <label class="label" id="user_name">投稿者名</label>
                        <div class="control">
                            <input id="user_name" name="user_name"
                                   class="input {{ $errors->has('user_name') ? 'is-danger' : '' }}" type="text"
                                   placeholder="スレッド投稿者名。"
                                   value="{{ old('user_name') ?: $topic->user_name }}">
                        </div>
                        @if($errors->has('user_name'))
                            <p class="help is-danger">{{ $errors->first('user_name') }}</p>
                        @endif
                    </div>


                    <div class="field is-grouped">
                        <div class="control">
                            <button class="button is-link" type="submit">更新する</button>
                        </div>
                        <div class="control">
                            <a class="button is-text" href="{{ route('topics.show', ['topic'=>$topic]) }}">キャンセル</a>
                        </div>
                    </div>


                </form>

            </div>
        </div>
    </div>

@endsection

resources/views/topics/index.blade.php
@extends('layout')

@section('content')

    <div class="columns is-variable bd-klmn-columns is-2">
        <div class="column is-9">
            <h2 class="title is-5">スレッド一覧</h2>
        </div>
        <div class="column is-3">
            <div class="buttons are-small is-right">
                <a class="button is-link" href="{{ route('topics.create') }}">スレッドの作成</a>
            </div>
        </div>
    </div>

    @foreach($topics as $topic)
        <article class="card">
            <div class="card-content">
                <div class="content">
                    <h2 class="title is-6">{{ $topic->title }}</h2>
                    <div class="field is-grouped is-grouped-multiline">
                        <div class="control">
                            <span class="tag">投稿日時: <time datetime="{{ $topic->created_at->format('Y.m.d') }}">{{ $topic->created_at->format('Y.m.d') }}</span></time>
                        </div>
                        <div class="control">
                            <span class="tag">コメント {{ $topic->comments->count() }}件</span>
                        </div>
                    </div>
                    <p class="is-size-7"><span>@</span>{{ empty($topic->user_name) ? '名無しの人' : $topic->user_name }}</p>
                    <p class="buttons are-small"><a class="button is-link" href="{{ route('topics.show', ['topic'=>$topic]) }}">詳細を見る</a></p>
                </div>
            </div>
        </article>
    @endforeach

    {{-- TODO: paginationのテンプレートの指定方法がこれで良いか不明 --}}
    {{ $topics->links('vendor.pagination.default') }}

@endsection

resources/views/topics/show.blade.php
@extends('layout')

@section('content')

    <div class="card">
        <header class="card-header">
            <p class="card-header-title">
                {{ $topic->title }}
            </p>
        </header>
        <div class="card-content">
            <div>
                <div class="content">
                    <div class="field is-grouped is-grouped-multiline">
                        <div class="control">
                            <span class="tag">投稿日時: <time
                                    datetime="{{ $topic->created_at->format('Y.m.d') }}">{{ $topic->created_at->format('Y.m.d') }}</span></time>
                        </div>
                        <div class="control">
                            <span class="tag">コメント {{ $topic->comments->count() }}件</span>
                        </div>
                    </div>
                    <p class="is-size-7"><span>@</span>{{ empty($topic->user_name) ? '名無しの人' : $topic->user_name }}</p>
                </div>

                <div class="buttons are-small is-right">
                    <a href="{{ route('top') }}" class="button">スレッド一覧へ</a>

                    <a href="{{ route('topics.edit', ['topic'=>$topic]) }}" class="button is-link">編集する</a>

                    <form method="POST" action="{{ route('topics.destroy', ['topic' => $topic]) }}" style="display: inline-block;">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="button is-danger btn-dell">削除する</button>
                    </form>

                </div>

                <!-- コメント -->
                <h2 class="title is-5">コメント</h2>
                <div class="box">

                    <form method="POST" action="{{ route('comments.store') }}">
                        @csrf

                        <input type="hidden" name="topic_id" value="{{ $topic->id }}">

                        <div class="field">
                            <label class="label" for="user_name">投稿者名</label>
                            <div class="control">
                                <input id="user_name" name="user_name"
                                       class="input {{ $errors->has('user_name') ? 'is-danger' : '' }}" type="text"
                                       placeholder="スレッド投稿者名。" value="{{ old('user_name') }}">
                            </div>

                            @if($errors->has('user_name'))
                                <p class="help is-danger">{{ $errors->first('user_name') }}</p>
                            @endif

                        </div>


                        <div class="field">
                            <label class="label" for="message">メッセージ</label>
                            <div class="control">
                                <textarea id="message" name="message"
                                          class="textarea {{ $errors->has('message') ? 'is-danger' : '' }}"
                                          placeholder="Textarea">{{ old('message') }}</textarea>
                            </div>

                            @if($errors->has('message'))
                                <p class="help is-danger">{{ $errors->first('message') }}</p>
                            @endif
                        </div>


                        <div class="field is-grouped">
                            <div class="control">
                                <button class="button is-link" type="submit">コメントをする</button>
                            </div>
                        </div>

                    </form>

                </div>


                <h2 class="title is-5">コメント一覧 ({{ $topic->comments->count() }})</h2>

                @if($comments->count())
                    <div class="box">

                        @foreach($comments as $comment)

                            <article class="media">
                                <div class="media-content">
                                    <h3 class="title is-6">{{ empty($comment->user_name) ? '名無しの人' : $comment->user_name }}</h3>
                                    <div class="content">
                                        <p>{!! nl2br(e($comment->message)) !!}</p>
                                        <p class="has-text-right">
                                            <small>{{ $comment->created_at->format('Y.m.d H:i') }}</small>
                                        </p>
                                    </div>
                                    <div class="buttons are-small is-right">
                                        <a href="{{ route('comments.edit', ['comment' => $comment]) }}" class="button is-link">編集する</a>

                                        <form method="POST" action="{{ route('comments.destroy', ['comment' => $comment]) }}" style="display: inline-block;">
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="button is-danger btn-dell">削除する</button>
                                        </form>

                                    </div>
                                </div>
                            </article>

                        @endforeach

                    </div>

                    {{ $comments->links('vendor.pagination.default') }}
                @else
                    <p>まだ、コメントはありません。</p>
                @endif

            </div>
        </div>
    </div>

    <script>
        window.addEventListener('load', ()=>{
            var $btnDell = document.getElementsByClassName('btn-dell');
            for (var i = 0; $btnDell.length > i; i++) {
                $btnDell[i].addEventListener('click', function(e) {
                    if(!confirm("本当に削除しますか？")){
                        e.preventDefault();
                        console.log('削除を中止しました。');
                    }
                })
            }
        });
    </script>


@endsection